version: '3'
services:
  node:
      build:
        context: .
        dockerfile: Dockerfile-dev
      user: "node"
      volumes:
      - ./:/usr/src/app
      ports: 
          - 8000:8000
      working_dir: /usr/src/app
      environment:
        - NODE_ENV=development
      expose:
        - "8000"