version: '3'
services:
  node:
      build: .
      user: "node"
      volumes:
      - ./:/usr/src/app
      ports: 
          - 127.0.0.1:8000:8000
      working_dir: /usr/src/app
      environment:
        - NODE_ENV=production
      expose:
        - "8000"