GET http://localhost:8000/users
###

GET http://localhost:8000/users/60afb1ced4d4779d0e1a4714
###

POST http://localhost:8000/register
Content-Type: application/json

{
    "lastName": "Durand",
    "firstName": "Jean",
    "birthdate": "1990-06-25",
    "adress": "13006 Marseille Avenue du Prado",
    "role": true,
    "civility": 1,
    "email": "jean.durand@mail.fr",
    "password": "azerty"
}
###

PATCH http://localhost:8000/users/6082bba64bd4b035736998e8
Content-Type: application/json

{
    "lastName": "Durand",
    "firstName": "Jean",
    "birthdate": "1990-06-25",
    "adress": "13006 Marseille Avenue du Prado",
    "role": false,
    "civility": 0,
    "email": "jean2@mail.fr",
    "password": "azerty"
}

###
DELETE http://localhost:8000/users/60a7e317a2a79c2501a9af76
