GET http://localhost:8000/coachs
###

GET http://localhost:8000/coachs/61603504a50318985782d674
###

POST http://localhost:8000/coachs
Content-Type: application/json

{
    "userId": "61693184aad9f75696aa46ad",
    "description": "coach sportif"
}

###

PATCH http://localhost:8000/coachs/61603504a50318985782d674
Content-Type: application/json

{
    "description": "coach en seduction"
}
###

DELETE http://localhost:8000/coachs/61603504a50318985782d674
###
