GET http://localhost:8000/messages
###

GET http://localhost:8000/messages/61a399e8259f509fa609285e
###

GET http://localhost:8000/messages/conversation/61a0f19fe649b274f73b8ca0
###

POST http://localhost:8000/messages/
Content-Type: application/json

{
    "conversationId" : "61a0f19fe649b274f73b8ca0",
    "userId": "616932566854306e86c2ca0e",
    "message": "Mes performences sont bonnes?"

}
###

PATCH http://localhost:8000/messages/61a398b6259f500b1e092854/
Content-Type: application/json

{
    "message": "Hello dear coach!"
}
###

DELETE http://localhost:8000/messages/61a398b6259f500b1e092854/
###
