GET http://localhost:8000/messages
###

GET http://localhost:8000/messages/614dea23d24e9528094b7558
###

GET http://localhost:8000/messages/user/60f1b59674af70801beba6e3
###

POST http://localhost:8000/messages
Content-Type: application/json

{
    "userId": "60f1b59674af70801beba6e3",
    "userIdRecever": "60f437cae3256550d7dc52f7",
    "message": "Hello coach!"

}
###

PATCH http://localhost:8000/messages/615ffe2fd3c76326ff7d5188
Content-Type: application/json

{
    "message": "Hello dear coach!"
}
###

DELETE http://localhost:8000/messages/614de9e9d24e956d094b7557
###
