GET http://localhost:8000/users
###

GET http://localhost:8000/users/61693184aad9f75696aa46ad
###

GET http://localhost:8000/users/coach/60f1b59674af70801beba6e3
###

POST http://localhost:8000/register
Content-Type: application/json

{
    "lastName": "Inshape",
    "firstName": "Tibo",
    "birthdate": "1995-01-01",
    "address": "2-4 Rue Philippe Lebon, 81000 Albi",
    "civility": 1,
    "email": "tibo.inshape@gmail.com",
    "password": "azerty",
    "coachId": ""
}
###

POST http://localhost:8000/register
Content-Type: application/json

{
    "lastName": "butin",
    "firstName": "jeremy",
    "birthdate": "1997-01-01",
    "address": "",
    "civility": 1,
    "email": "jeremy.butin@epitech.eu",
    "password": "azerty",
    "coachId": "61693184aad9f75696aa46ad"
}
###


POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "jean.durand4@mail.fr",
    "password": "azerty"
}
###

PATCH http://localhost:8000/users/61693184aad9f75696aa46ad
Content-Type: application/json

{
    "coachId": "61693184aad9f75696aa46ad"
}
###

PATCH http://localhost:8000/users/60f443acbd84db7a98340826
Content-Type: application/json

{
    "coachId": "61603504a50318985782d674"
}

###
DELETE http://localhost:8000/users/60ba3cad96a985677d8113a7
