GET http://localhost:8000/users
###

GET http://localhost:8000/users/60f1b59674af70801beba6e3
###

POST http://localhost:8000/register
Content-Type: application/json

{
    "lastName": "Durand",
    "firstName": "Jean",
    "birthdate": "1990-07-18T14:16:42.840+00:00",
    "address": "13006 Marseille Avenue du Prado",
    "role": true,
    "civility": 1,
    "email": "jean.durand4@mail.fr",
    "password": "azerty"
}
###


POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "jean.durand4@mail.fr",
    "password": "azerty"
}
###

PATCH http://localhost:8000/users/6082bba64bd4b035736998e8
Content-Type: application/json

{
    "lastName": "Durand",
    "firstName": "Jean",
    "birthdate": "1990-06-25",
    "address": "13006 Marseille Avenue du Prado",
    "role": false,
    "civility": 0,
    "email": "jean2@mail.fr",
    "password": "azerty"
}

###
DELETE http://localhost:8000/users/60ba3cad96a985677d8113a7
